/** Local Anvil only. Random ephemeral keys and mock tokens; never connects to public RPC. */
import { createPublicClient, createWalletClient, http, encodeFunctionData, decodeEventLog, keccak256, sha256, stringToHex, bytesToHex, encodeAbiParameters, hashMessage, ContractFunctionRevertedError, type Hex, type Address } from 'viem';
import { generatePrivateKey, privateKeyToAccount } from 'viem/accounts';
import { foundry } from 'viem/chains';
import { actionMessage, actionDomain, ACTION_TYPES, hashActionIntent, ZERO_ADDRESS, type ActionIntent } from '@steward/shared';
import { readFile } from 'node:fs/promises';
import { VerifiedLiveChainGateway } from '../server/src/integrations/live-chain';
import { createApp } from '../server/src/app';
import { createDatabase } from '../server/src/db';
import { ReadRpcPool } from '../server/src/integrations/rpc';
const artifact = async (name: string) => JSON.parse(await readFile(`contracts/out/${name}.sol/${name}.json`, 'utf8'));
const passkeyOnly=process.argv.includes('--passkey-auth-only');
const port = 18000 + Math.floor(Math.random()*10000);
const processHandle = Bun.spawn(['anvil','--host','127.0.0.1','--port',String(port),'--chain-id','31337','--timestamp',String(Math.floor(Date.now()/1000)-(passkeyOnly?0:172800)),'--silent'], {stdout:'pipe',stderr:'pipe'});
const url = `http://127.0.0.1:${port}`;
const client = createPublicClient({chain:foundry,transport:http(url)});
const parent = privateKeyToAccount(generatePrivateKey()), caregiver=privateKeyToAccount(generatePrivateKey());
const wallet=createWalletClient({account:parent,chain:foundry,transport:http(url)});
const accounts=Array.from({length:6},()=>privateKeyToAccount(generatePrivateKey()).address);
let checks=0;
const check=(condition:unknown,message:string)=>{if(!condition)throw new Error(message);checks++;};
async function rpc(method:string,params:unknown[]) { const res=await fetch(url,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({jsonrpc:'2.0',id:1,method,params})});const body=await res.json() as any;if(body.error)throw Error(body.error.message);return body.result; }
async function mined(hash:Hex) {const receipt=await client.waitForTransactionReceipt({hash});check(receipt.status==='success','transaction reverted');return receipt;}
async function deploy(name:string,args:unknown[]) {const a=await artifact(name); const result=await mined(await wallet.deployContract({abi:a.abi,bytecode:a.bytecode.object,args}));return {abi:a.abi,address:result.contractAddress!};}
async function rejected(operation:()=>Promise<unknown>,message:string) {let failed=false;try{await operation();}catch(error){const walked=(error as any)?.walk;failed=error instanceof ContractFunctionRevertedError||(typeof walked==='function'&&walked((entry:unknown)=>entry instanceof ContractFunctionRevertedError)!==undefined);}check(failed,message);}
async function failed(operation:()=>Promise<unknown>,message:string) {let didFail=false;try{await operation();}catch{didFail=true;}check(didFail,message);}
try {
  let ready=false;for(let i=0;i<50;i++){try{if(processHandle.exitCode!==null)throw new Error('Owned Anvil exited');if(await client.getChainId()===31337){ready=true;break;}}catch{}await Bun.sleep(100);}if(!ready)throw new Error('Local Anvil did not start');
  await rpc('anvil_setBalance',[parent.address,'0x3635c9adc5dea00000']);
  await rpc('anvil_setBalance',[caregiver.address,'0x3635c9adc5dea00000']);
  const passkeyGateway=new VerifiedLiveChainGateway({rpc:new ReadRpcPool([url],31337,fetch,()=>Date.now()-(passkeyOnly?0:172800000)),manifest:{chainId:31337,version:'steward-account-v1',accounts:[],routes:[]}});
  // Real P-256 signatures generated for this local fixture; no user credential is accessed.
  const keypair=await crypto.subtle.generateKey({name:'ECDSA',namedCurve:'P-256'},true,['sign','verify']);
  const pub=new Uint8Array(await crypto.subtle.exportKey('raw',keypair.publicKey));
  const rpHash=sha256(stringToHex('localhost'));
  const signer=await deploy('StewardPasskeySignerV1',[rpHash,'http://localhost:5173',bytesToHex(pub.slice(1,33)),bytesToHex(pub.slice(33)),1n]);
  const assertion=async(digest:Hex)=>{
    const auth=new Uint8Array(37);auth.set(Buffer.from(rpHash.slice(2),'hex'));auth[32]=5;
    const clientJson=JSON.stringify({type:'webauthn.get',challenge:Buffer.from(digest.slice(2),'hex').toString('base64url'),origin:'http://localhost:5173',crossOrigin:false});
    const signed=new Uint8Array(69);signed.set(auth);signed.set(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(clientJson))),37);
    const signature=new Uint8Array(await crypto.subtle.sign({name:'ECDSA',hash:'SHA-256'},keypair.privateKey,signed));
    const n=0xffffffff00000000ffffffffffffffffbce6faada7179e84f3b9cac2fc632551n;
    const scalar=BigInt(bytesToHex(signature.slice(32))),low=scalar>n/2n?n-scalar:scalar;
    return encodeAbiParameters([{type:'bytes'},{type:'string'},{type:'bytes32'},{type:'bytes32'}],[bytesToHex(auth),clientJson,bytesToHex(signature.slice(0,32)),`0x${low.toString(16).padStart(64,'0')}`]);
  };
  const message='Local generated authenticator integration fixture',sig=await assertion(hashMessage(message));
  check(await passkeyGateway.verifyWalletSignature({address:signer.address,message,signature:sig}),'real P256 ERC1271 signature rejected');
  check(!await passkeyGateway.verifyWalletSignature({address:signer.address,message:message+' changed',signature:sig}),'P256 altered challenge accepted');
  const passkeyDb=createDatabase(':memory:');try{
    const api=createApp({db:passkeyDb,chain:passkeyGateway,config:{origin:'http://localhost:5173',serviceKey:crypto.getRandomValues(new Uint8Array(32))}});
    const headers={origin:'http://localhost:5173','content-type':'application/json'};
    const response=await api.request('http://localhost/api/v1/auth/webauthn/challenges',{method:'POST',headers,body:JSON.stringify({address:signer.address,chainId:31337})});const challenge=(await response.json()).data;
    const signed=await assertion(challenge.challengeDigest);
    const session=await api.request('http://localhost/api/v1/auth/webauthn/sessions',{method:'POST',headers,body:JSON.stringify({address:signer.address,challengeId:challenge.challengeId,signature:signed})});check(session.status===200,'onchain-verified passkey API login failed');
  }finally{passkeyDb.close();}
  if(!process.argv.includes('--passkey-auth-only')){
  const token=await deploy('MockStewardToken',['Demo settlement','USDG',6]);
  const stock=await deploy('MockStewardToken',['Demo stock','DSTK',18]);
  const source=await deploy('MockPriceSource',[]);
  const venue=await deploy('MockStewardVenue',[]);
  const settlementFeed=accounts[0],stockFeed=accounts[1];
  await mined(await wallet.writeContract({...source,functionName:'setFeed',args:[token.address,settlementFeed]}));
  await mined(await wallet.writeContract({...source,functionName:'setFeed',args:[stock.address,stockFeed]}));
  const observedAt=(await client.getBlock()).timestamp;
  await mined(await wallet.writeContract({...source,functionName:'set',args:[token.address,100_000_000n,8,observedAt,false]}));
  await mined(await wallet.writeContract({...source,functionName:'set',args:[stock.address,50_000_000n,8,observedAt,false]}));
  const adapter=await deploy('StewardTradeAdapterV1',[token.address,venue.address,source.address,3600n,500n,[stock.address],[stockFeed]]);
  await mined(await wallet.writeContract({...venue,functionName:'setRate',args:[token.address,stock.address,2_000_000_000_000_000_000_000_000_000_000n]}));
  await mined(await wallet.writeContract({...venue,functionName:'setRate',args:[stock.address,token.address,500_000n]}));
  await mined(await wallet.writeContract({...stock,functionName:'mint',args:[venue.address,1_000_000n*10n**18n]}));
  const config={settlement:token.address,period:86400n,anchor:0n,paymentLimit:500_000_000n,buyLimit:1_000_000_000n,reserve:100_000_000n,perPayment:500_000_000n,perBuy:1_000_000_000n,perSell:100n*10n**18n,exceptionQuorum:2n,approvedTokens:[stock.address],paymentRecipients:[accounts[0]],exceptionSigners:[accounts[1],accounts[2]],guardians:[accounts[3],accounts[4],accounts[5]],approvedAdapters:[],sellCapTokens:[stock.address],sellCaps:[100n*10n**18n],continuityReviewer:ZERO_ADDRESS,continuitySuccessor:ZERO_ADDRESS,continuityPlanHash:`0x${'00'.repeat(32)}`};
  const factory=await deploy('StewardFactoryV1',[]);
  const created=await mined(await wallet.writeContract({...factory,functionName:'createAccount',args:[parent.address,config]}));
  const createdEvent=created.logs.map(log=>{try{return decodeEventLog({abi:factory.abi,data:log.data,topics:log.topics}) as any;}catch{return null;}}).find(e=>e?.eventName==='AccountCreated');
  check(Boolean(createdEvent),'factory creation event missing');
  const account={address:createdEvent.args.account as Address,abi:(await artifact('StewardAccountV1')).abi};
  const implementation=await client.readContract({...factory,functionName:'implementation'}) as Address;
  await mined(await wallet.writeContract({...token,functionName:'mint',args:[account.address,10_000_000_000n]}));
  let now=Number((await client.getBlock()).timestamp);
  await mined(await wallet.writeContract({...account,functionName:'setDelegate',args:[caregiver.address,7n,BigInt(now+86400*30),100n*10n**18n]}));
  check((await client.readContract({...account,functionName:'delegates',args:[caregiver.address]}) as readonly unknown[])[4]===true,'caregiver grant was not active immediately');
  await mined(await wallet.writeContract({...account,functionName:'admitAdapter',args:[adapter.address,true]}));
  await rpc('evm_increaseTime',[172801]);await rpc('evm_mine',[]);
  await mined(await wallet.writeContract({...account,functionName:'executeAdapterAdmission'}));
  now=Number((await client.getBlock()).timestamp);
  await mined(await wallet.writeContract({...source,functionName:'set',args:[token.address,100_000_000n,8,BigInt(now),false]}));
  await mined(await wallet.writeContract({...source,functionName:'set',args:[stock.address,50_000_000n,8,BigInt(now),false]}));
  now=Number((await client.getBlock()).timestamp);
  const version=(await client.readContract({...account,functionName:'policy'}) as readonly bigint[])[10]!;
  const intent:ActionIntent={actionId:`0x${'01'.repeat(32)}`,kind:'PAYMENT',account:account.address,actor:caregiver.address,chainId:31337,securityEpoch:'1',policyVersion:version.toString(),nonce:'1',tokenIn:token.address,tokenOut:ZERO_ADDRESS,recipient:accounts[0]!,amountInRaw:'100000000',minAmountOutRaw:'0',adapter:ZERO_ADDRESS,routeHash:`0x${'00'.repeat(32)}`,validAfter:String(now-1),deadline:String(now+3600),exceptionMask:'0'};
  const digest=hashActionIntent(intent);
  check(digest===await client.readContract({...account,functionName:'actionHash',args:[actionMessage(intent)]}),'JS/Solidity EIP712 hash mismatch');
  const signature=await caregiver.signTypedData({domain:actionDomain(intent),types:ACTION_TYPES,primaryType:'Action',message:actionMessage(intent)});
  const runtimeCode=await client.getCode({address:account.address});
  const gateway=new VerifiedLiveChainGateway({rpc:new ReadRpcPool([url],31337),manifest:{chainId:31337,version:'steward-account-v1',accounts:[{address:account.address,runtimeCodeHash:keccak256(runtimeCode!),settlement:token.address,deploymentBlock:created.blockNumber.toString(),implementation,implementationCodeHash:keccak256((await client.getCode({address:implementation}))!)}],routes:[],factory:{address:factory.address,runtimeCodeHash:keccak256((await client.getCode({address:factory.address}))!),implementation,implementationCodeHash:keccak256((await client.getCode({address:implementation}))!)}}});
  await rpc('anvil_mine',['0x40','0x0']);
  const accessKit=await gateway.getIndependentAccessKit(account.address);
  check(accessKit.verification.status==='verified-at-finalized-block','independent access kit was not finalized-verified');
  check(accessKit.contracts.account.abi.some((entry:any)=>entry.type==='function'&&entry.name==='withdraw'),'independent access kit omitted owner withdrawal ABI');
  const pinnedImplementationHash=gateway.options.manifest.accounts[0]!.implementationCodeHash!;
  gateway.options.manifest.accounts[0]!.implementationCodeHash=`0x${'11'.repeat(32)}`;
  await failed(()=>gateway.getIndependentAccessKit(account.address),'mismatched implementation pin was accepted');
  gateway.options.manifest.accounts[0]!.implementationCodeHash=pinnedImplementationHash;
  const configJson=JSON.parse(JSON.stringify(config,(_key,value)=>typeof value==='bigint'?value.toString():value));
  const deployment=await gateway.prepareDeployment(parent.address,configJson);
  const newReceipt=await mined(await wallet.sendTransaction({to:deployment.to as Address,data:deployment.data as Hex}));
  let pendingFinalityRejected=false;try{await gateway.confirmDeployment({transactionHash:newReceipt.transactionHash,parent:parent.address});}catch(error){pendingFinalityRejected=String(error).includes('DEPLOYMENT_NOT_FINALIZED');}check(pendingFinalityRejected,'unfinalized deployment was registered');
  await rpc('anvil_mine',['0x40','0x0']);
  const proof=await gateway.confirmDeployment({transactionHash:newReceipt.transactionHash,parent:parent.address});
  check(proof.parent.toLowerCase()===parent.address.toLowerCase()&&proof.policyVersion==='1','verified factory registration failed');
  let wrongParentRejected=false;try{await gateway.confirmDeployment({transactionHash:newReceipt.transactionHash,parent:caregiver.address});}catch{wrongParentRejected=true;}check(wrongParentRejected,'factory proof accepted wrong parent');
  const db=createDatabase(':memory:');
  try{
    const api=createApp({db,chain:gateway,config:{origin:'http://localhost:5173',serviceKey:crypto.getRandomValues(new Uint8Array(32)),secureCookies:false}});
    const headers={origin:'http://localhost:5173','content-type':'application/json'};
    let response=await api.request('http://localhost/api/v1/auth/challenges',{method:'POST',headers,body:JSON.stringify({address:parent.address,chainId:31337})});
    const challenge=(await response.json()).data;
    response=await api.request('http://localhost/api/v1/auth/sessions',{method:'POST',headers,body:JSON.stringify({challengeId:challenge.challengeId,address:parent.address,signature:await parent.signMessage({message:challenge.message})})});
    check(response.status===200,'real wallet session failed');
    const cookie=response.headers.get('set-cookie')!.split(';')[0]!;
    response=await api.request('http://localhost/api/v1/accounts/register-deployment',{method:'POST',headers:{...headers,cookie},body:JSON.stringify({transactionHash:newReceipt.transactionHash})});
    check(response.status===200,'real factory API registration failed');
    const registered=(await response.json()).data;
    response=await api.request(`http://localhost/api/v1/accounts/${registered.accountId}/policy`,{headers:{cookie}});
    check(response.status===200,'registered account policy read failed');
  }finally{db.close();}
  const prepared=await gateway.prepareAction(intent,[{signer:caregiver.address,signature,signatureType:'eoa'}]);
  const data=prepared.data as Hex;
  check(prepared.actionHash===digest,'gateway changed action hash');
  const receipt=await mined(await wallet.sendTransaction({to:account.address,data}));
  const inspected=await gateway.inspectTransaction(receipt.transactionHash,intent);
  check(['included','finalized'].includes(inspected.state),'gateway did not verify actual event receipt');
  check(inspected.actionHash===digest,'receipt action mismatch');
  check(await client.readContract({...token,functionName:'balanceOf',args:[accounts[0]]})===100_000_000n,'recipient balance mismatch');
  check((await gateway.getBudget(account.address)).remainingRaw==='400000000','daily budget not consumed');
  check((await gateway.getAccountHoldings(account.address, caregiver.address))[0]?.balanceRaw==='9900000000','live holdings were not read from chain');
  let replayRejected=false;try{await client.call({account:parent.address,to:account.address,data});}catch{replayRejected=true;}check(replayRejected,'signature replay accepted');
  let substitutedRejected=false;try{await client.call({account:parent.address,to:account.address,data:encodeFunctionData({abi:account.abi,functionName:'executePayment',args:[{...actionMessage(intent),nonce:2n,recipient:parent.address},[signature]]})});}catch{substitutedRejected=true;}check(substitutedRejected,'recipient substitution accepted');
  const routeHash=await client.readContract({...adapter,functionName:'routeHash',args:[token.address,stock.address]}) as Hex;
  const sellRouteHash=await client.readContract({...adapter,functionName:'routeHash',args:[stock.address,token.address]}) as Hex;
  const floor=await client.readContract({...adapter,functionName:'independentFloor',args:[token.address,stock.address,100_000_000n]}) as bigint;
  const buyIntent:ActionIntent={actionId:`0x${'02'.repeat(32)}`,kind:'BUY',account:account.address,actor:caregiver.address,chainId:31337,securityEpoch:'1',policyVersion:version.toString(),nonce:'2',tokenIn:token.address,tokenOut:stock.address,recipient:account.address,amountInRaw:'100000000',minAmountOutRaw:floor.toString(),adapter:adapter.address,routeHash,validAfter:String(now-1),deadline:String(now+3600),exceptionMask:'0'};
  const buyDigest=hashActionIntent(buyIntent);const buySignature=await caregiver.signTypedData({domain:actionDomain(buyIntent),types:ACTION_TYPES,primaryType:'Action',message:actionMessage(buyIntent)});
  const buyBeforeSettlement=await client.readContract({...token,functionName:'balanceOf',args:[account.address]}) as bigint;
  const buyBeforeStock=await client.readContract({...stock,functionName:'balanceOf',args:[account.address]}) as bigint;
  const buyReceipt=await mined(await wallet.writeContract({...account,functionName:'executeTrade',args:[actionMessage(buyIntent),[buySignature]]}));
  check((await client.readContract({...token,functionName:'balanceOf',args:[account.address]}) as bigint)===buyBeforeSettlement-100_000_000n,'buy settlement balance mismatch');
  check((await client.readContract({...stock,functionName:'balanceOf',args:[account.address]}) as bigint)===buyBeforeStock+200n*10n**18n,'buy output balance mismatch');
  check((await client.readContract({...token,functionName:'allowance',args:[account.address,adapter.address]}) as bigint)===0n,'account->adapter buy allowance not reset');
  check((await client.readContract({...token,functionName:'allowance',args:[adapter.address,venue.address]}) as bigint)===0n,'adapter->venue buy allowance not reset');
  check(buyDigest===await client.readContract({...account,functionName:'actionHash',args:[actionMessage(buyIntent)]}),'BUY EIP712 hash mismatch');
  const lowFloor={...buyIntent,actionId:`0x${'03'.repeat(32)}`,nonce:'3',minAmountOutRaw:(floor-1n).toString()};
  const lowFloorSignature=await caregiver.signTypedData({domain:actionDomain(lowFloor),types:ACTION_TYPES,primaryType:'Action',message:actionMessage(lowFloor)});
  await rejected(()=>client.simulateContract({...account,account:parent.address,functionName:'executeTrade',args:[actionMessage(lowFloor),[lowFloorSignature]]}),'adapter accepted output below independent price floor');
  const overCap={...buyIntent,actionId:`0x${'04'.repeat(32)}`,nonce:'4',amountInRaw:'1000000001',minAmountOutRaw:(await client.readContract({...adapter,functionName:'independentFloor',args:[token.address,stock.address,1_000_000_001n]}) as bigint).toString()};
  const overCapSignature=await caregiver.signTypedData({domain:actionDomain(overCap),types:ACTION_TYPES,primaryType:'Action',message:actionMessage(overCap)});
  await rejected(()=>client.simulateContract({...account,account:parent.address,functionName:'executeTrade',args:[actionMessage(overCap),[overCapSignature]]}),'BUY above policy cap was accepted');
  const sellFloor=await client.readContract({...adapter,functionName:'independentFloor',args:[stock.address,token.address,1n*10n**18n]}) as bigint;
  const sellIntent:ActionIntent={actionId:`0x${'05'.repeat(32)}`,kind:'SELL',account:account.address,actor:caregiver.address,chainId:31337,securityEpoch:'1',policyVersion:version.toString(),nonce:'5',tokenIn:stock.address,tokenOut:token.address,recipient:account.address,amountInRaw:(1n*10n**18n).toString(),minAmountOutRaw:sellFloor.toString(),adapter:adapter.address,routeHash:sellRouteHash,validAfter:String(now-1),deadline:String(now+3600),exceptionMask:'0'};
  const sellSignature=await caregiver.signTypedData({domain:actionDomain(sellIntent),types:ACTION_TYPES,primaryType:'Action',message:actionMessage(sellIntent)});
  const sellBeforeSettlement=await client.readContract({...token,functionName:'balanceOf',args:[account.address]}) as bigint;
  const sellBeforeStock=await client.readContract({...stock,functionName:'balanceOf',args:[account.address]}) as bigint;
  await mined(await wallet.writeContract({...account,functionName:'executeTrade',args:[actionMessage(sellIntent),[sellSignature]]}));
  check((await client.readContract({...stock,functionName:'balanceOf',args:[account.address]}) as bigint)===sellBeforeStock-1n*10n**18n,'sell input balance mismatch');
  check((await client.readContract({...token,functionName:'balanceOf',args:[account.address]}) as bigint)===sellBeforeSettlement+500_000n,'sell output balance mismatch');
  check((await client.readContract({...stock,functionName:'allowance',args:[account.address,adapter.address]}) as bigint)===0n,'account->adapter sell allowance not reset');
  check((await client.readContract({...stock,functionName:'allowance',args:[adapter.address,venue.address]}) as bigint)===0n,'adapter->venue sell allowance not reset');
  const overSell={...sellIntent,actionId:`0x${'06'.repeat(32)}`,nonce:'6',amountInRaw:(100n*10n**18n+1n).toString(),minAmountOutRaw:'1'};
  const overSellSignature=await caregiver.signTypedData({domain:actionDomain(overSell),types:ACTION_TYPES,primaryType:'Action',message:actionMessage(overSell)});
  await rejected(()=>client.simulateContract({...account,account:parent.address,functionName:'executeTrade',args:[actionMessage(overSell),[overSellSignature]]}),'SELL above token cap was accepted');
  check(buyReceipt.status==='success','BUY receipt missing');
  const passkeyCreated=await mined(await wallet.writeContract({...factory,functionName:'createAccount',args:[signer.address,config]}));
  const event=passkeyCreated.logs.map(log=>{try{return decodeEventLog({abi:factory.abi,data:log.data,topics:log.topics}) as any;}catch{return null;}}).find(e=>e?.eventName==='AccountCreated');
  const passkeyAccount=event.args.account as Address;await mined(await wallet.writeContract({...token,functionName:'mint',args:[passkeyAccount,100n]}));
  const withdraw=encodeFunctionData({abi:account.abi,functionName:'withdraw',args:[token.address,100n,parent.address]});
  const deadline=(await client.getBlock()).timestamp+300n;
  const callDigest=await client.readContract({...signer,functionName:'callHash',args:[passkeyAccount,0n,withdraw,0n,deadline]}) as Hex;
  const signedCall=await assertion(callDigest);
  await mined(await wallet.writeContract({...signer,functionName:'execute',args:[passkeyAccount,0n,withdraw,0n,deadline,signedCall]}));
  check(await client.readContract({...token,functionName:'balanceOf',args:[passkeyAccount]})===0n,'passkey sponsored owner withdrawal failed');
  let callReplayRejected=false;try{await client.simulateContract({...signer,account:parent.address,functionName:'execute',args:[passkeyAccount,0n,withdraw,0n,deadline,signedCall]});}catch{callReplayRejected=true;}check(callReplayRejected,'sponsored passkey call replay accepted');
  }
  console.log(JSON.stringify({status:'passed',checks,chainId:31337,scope:process.argv.includes('--passkey-auth-only')?'local generated P256 signer and onchain-verified API login only':'local mock token; exact payment plus guarded adapter BUY/SELL, finalized access kit, generated P256 API login and sponsored owner withdrawal',realFunds:false}));
} finally {processHandle.kill();await processHandle.exited;}
